server:
  port: 7000
#服务名字
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#git 仓库的地址
          uri: https://github.com/dhlldq/spring-cloud-config-repository.git
#git 仓库的账号密码
          username: dhlldq
          password: 091322ldq
#加入注册中心，实现高可用
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
